version: '3.8'
services:
  db:
    image: postgis/postgis:16-3.4  
    container_name: postgres_postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: shek
      POSTGRES_PASSWORD: shek
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
